// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: community.sql

package db

import (
	"context"
)

const listMessages = `-- name: ListMessages :many
SELECT id, user_id, room, body, created_at FROM community_message
WHERE room = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListMessagesParams struct {
	Room  string `json:"room"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]CommunityMessage, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.Room, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommunityMessage
	for rows.Next() {
		var i CommunityMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Room,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postMessage = `-- name: PostMessage :one
INSERT INTO community_message (user_id, room, body)
VALUES ($1, $2, $3)
RETURNING id, user_id, room, body, created_at
`

type PostMessageParams struct {
	UserID string `json:"user_id"`
	Room   string `json:"room"`
	Body   string `json:"body"`
}

func (q *Queries) PostMessage(ctx context.Context, arg PostMessageParams) (CommunityMessage, error) {
	row := q.db.QueryRow(ctx, postMessage, arg.UserID, arg.Room, arg.Body)
	var i CommunityMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Room,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}
