// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHealthRecord = `-- name: CreateHealthRecord :one
INSERT INTO health_record (user_id, kind, triage_level, notes)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, kind, triage_level, notes, created_at
`

type CreateHealthRecordParams struct {
	UserID      string      `json:"user_id"`
	Kind        string      `json:"kind"`
	TriageLevel pgtype.Text `json:"triage_level"`
	Notes       string      `json:"notes"`
}

func (q *Queries) CreateHealthRecord(ctx context.Context, arg CreateHealthRecordParams) (HealthRecord, error) {
	row := q.db.QueryRow(ctx, createHealthRecord,
		arg.UserID,
		arg.Kind,
		arg.TriageLevel,
		arg.Notes,
	)
	var i HealthRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.TriageLevel,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listHealthRecordsByUser = `-- name: ListHealthRecordsByUser :many
SELECT id, user_id, kind, triage_level, notes, created_at FROM health_record
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListHealthRecordsByUser(ctx context.Context, userID string) ([]HealthRecord, error) {
	rows, err := q.db.Query(ctx, listHealthRecordsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HealthRecord
	for rows.Next() {
		var i HealthRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.TriageLevel,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
