// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"
)

const createMediaObject = `-- name: CreateMediaObject :one
INSERT INTO media_object (user_id, bucket, object_key, content_type)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, bucket, object_key, content_type, created_at
`

type CreateMediaObjectParams struct {
	UserID      string `json:"user_id"`
	Bucket      string `json:"bucket"`
	ObjectKey   string `json:"object_key"`
	ContentType string `json:"content_type"`
}

func (q *Queries) CreateMediaObject(ctx context.Context, arg CreateMediaObjectParams) (MediaObject, error) {
	row := q.db.QueryRow(ctx, createMediaObject,
		arg.UserID,
		arg.Bucket,
		arg.ObjectKey,
		arg.ContentType,
	)
	var i MediaObject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bucket,
		&i.ObjectKey,
		&i.ContentType,
		&i.CreatedAt,
	)
	return i, err
}
