// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string             `json:"id"`
	UserId                string             `json:"userId"`
	AccountId             string             `json:"accountId"`
	ProviderId            string             `json:"providerId"`
	AccessToken           pgtype.Text        `json:"accessToken"`
	RefreshToken          pgtype.Text        `json:"refreshToken"`
	IdToken               pgtype.Text        `json:"idToken"`
	AccessTokenExpiresAt  pgtype.Timestamptz `json:"accessTokenExpiresAt"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refreshTokenExpiresAt"`
	Scope                 pgtype.Text        `json:"scope"`
	Password              pgtype.Text        `json:"password"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

type CommunityMessage struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    string             `json:"user_id"`
	Room      string             `json:"room"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type HealthRecord struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      string             `json:"user_id"`
	Kind        string             `json:"kind"`
	TriageLevel pgtype.Text        `json:"triage_level"`
	Notes       string             `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MediaObject struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      string             `json:"user_id"`
	Bucket      string             `json:"bucket"`
	ObjectKey   string             `json:"object_key"`
	ContentType string             `json:"content_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID        string             `json:"id"`
	UserId    string             `json:"userId"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
	IpAddress pgtype.Text        `json:"ipAddress"`
	UserAgent pgtype.Text        `json:"userAgent"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type User struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"emailVerified"`
	Image         pgtype.Text        `json:"image"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

type Verification struct {
	ID         string             `json:"id"`
	Identifier string             `json:"identifier"`
	Value      string             `json:"value"`
	ExpiresAt  pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
}

type WaitlistSignup struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	Stage       string             `json:"stage"`
	Location    string             `json:"location"`
	Support     string             `json:"support"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ConsentedAt pgtype.Timestamptz `json:"consented_at"`
}
