// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: waitlist.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptWaitlistSignup = `-- name: AcceptWaitlistSignup :exec
UPDATE waitlist_signup
SET status = 'accepted'
WHERE id = $1
`

func (q *Queries) AcceptWaitlistSignup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, acceptWaitlistSignup, id)
	return err
}

const createWaitlistSignup = `-- name: CreateWaitlistSignup :one
INSERT INTO waitlist_signup (name, email, stage, location, support)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (lower(email)) DO NOTHING
RETURNING id, name, email, stage, location, support, status, created_at
`

type CreateWaitlistSignupParams struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Stage    string `json:"stage"`
	Location string `json:"location"`
	Support  string `json:"support"`
}

func (q *Queries) CreateWaitlistSignup(ctx context.Context, arg CreateWaitlistSignupParams) (WaitlistSignup, error) {
	row := q.db.QueryRow(ctx, createWaitlistSignup,
		arg.Name,
		arg.Email,
		arg.Stage,
		arg.Location,
		arg.Support,
	)
	var i WaitlistSignup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Stage,
		&i.Location,
		&i.Support,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listWaitlistSignups = `-- name: ListWaitlistSignups :many
SELECT id, name, email, stage, location, support, status, created_at FROM waitlist_signup
ORDER BY created_at DESC
`

func (q *Queries) ListWaitlistSignups(ctx context.Context) ([]WaitlistSignup, error) {
	rows, err := q.db.Query(ctx, listWaitlistSignups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaitlistSignup
	for rows.Next() {
		var i WaitlistSignup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Stage,
			&i.Location,
			&i.Support,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
